import type { CharacterSheet } from "../interfaces/sheet";

export function convertToCharacterSheet(data: any): CharacterSheet {
  return {
    nomePersonagem: data.caracteristicas?.nomePersonagem ?? "",
    idClasse: data.caracteristicas?.idClasse ?? "",
    idRaca: data.caracteristicas?.idRaca ?? "",
    antecedente: data.caracteristicas?.antecedente ?? "",
    tendencia: data.caracteristicas?.tendencia ?? "",
    xp: String(data.caracteristicas?.xp ?? ""),
    nivel: String(data.nivel ?? ""),
    atributos: {
      forca: data.atributos?.forca ?? 10,
      destreza: data.atributos?.destreza ?? 10,
      constituicao: data.atributos?.constituicao ?? 10,
      inteligencia: data.atributos?.inteligencia ?? 10,
      sabedoria: data.atributos?.sabedoria ?? 10,
      carisma: data.atributos?.carisma ?? 10,
    },
    inspiracao: data.inspiracao ?? false,
    pericias: {
      acrobacia: data.pericias?.acrobacia ?? false,
      arcanismo: data.pericias?.arcanismo ?? false,
      atletismo: data.pericias?.atletismo ?? false,
      atuacao: data.pericias?.atuacao ?? false,
      blefar: data.pericias?.blefar ?? false,
      carisma: data.pericias?.carisma ?? false,
      constituicao: data.pericias?.constituicao ?? false,
      destreza: data.pericias?.destreza ?? false,
      enganacao: data.pericias?.enganacao ?? false,
      forca: data.pericias?.forca ?? false,
      furtividade: data.pericias?.furtividade ?? false,
      historia: data.pericias?.historia ?? false,
      intimidacao: data.pericias?.intimidacao ?? false,
      intuicao: data.pericias?.intuicao ?? false,
      investigacao: data.pericias?.investigacao ?? false,
      lidarComAnimais: data.pericias?.lidar_com_animais ?? false,
      medicina: data.pericias?.medicina ?? false,
      natureza: data.pericias?.natureza ?? false,
      percepcao: data.pericias?.percepcao ?? false,
      persuasao: data.pericias?.persuasao ?? false,
      prestidigitacao: data.pericias?.prestigitacao ?? false,
      religiao: data.pericias?.religiao ?? false,
      sabedoria: data.pericias?.sabedoria ?? false,
      sobrevivencia: data.pericias?.sobrevivencia ?? false,
      inteligencia: data.pericias?.inteligencia ?? false,
    },
    idiomas: data.caracteristicas?.idiomas ?? "",
    deslocamento: String(data.deslocamento ?? ""),
    pontosVidaBase: String(data.pontosVidaBase ?? ""),
    vidaTemporaria: String(data.vidaTemporaria ?? ""),
    dadoDeVida: String(data.dadoDeVida ?? ""),
    inventario: {
      pc: data.inventario?.pc ?? 0,
      pp: data.inventario?.pp ?? 0,
      pe: data.inventario?.pe ?? 0,
      po: data.inventario?.po ?? 0,
      pl: data.inventario?.pl ?? 0,
      itens: data.inventario?.itens ?? "",
    },
    descricao: {
      personalidade: data.descricao?.personalidade ?? "",
      ideal: data.descricao?.ideal ?? "",
      ligacao: data.descricao?.ligacao ?? "",
      defeito: data.descricao?.defeitos ?? "",
      proficiencia: data.caracteristicas?.proficiencias ?? "",
      historia: data.descricao?.historia ?? "",
        aparencia: data.descricao?.aparencia ?? "",
    },
  };
}
